#!/bin/sh

if type "kill" > /dev/null 2>&1; then
  function kill-ift {
    for pid in `\ps aux | $IFT | awk '{ print $2 }'`
    do
      kill -9 $pid
    done
  }

  alias kif="kill-ift"
fi

if type "ssh" > /dev/null 2>&1; then
  function ssh-ift {
    local selected_hosts=$(awk '
      tolower($1)=="host" {
        for (i=2; i<=NF; i++) {
          if ($i !~ "[*?]") {
            print $i
          }
        }
      }
    ' ~/.ssh/config | sort | $IFT --query "$LBUFFER")
    if [ -n "$selected_hosts" ]; then
      ssh $selected_hosts
    fi
  }

  alias sif="ssh-ift"
fi

if type "ssh-add" > /dev/null 2>&1; then
  function ssh-add-ift {
    local identityfiles=`find $HOME/.ssh -type f -perm 600 -not -name config | $IFT`
    if [ -n "$identityfiles" ]; then
      ssh-add $identityfiles
    fi
  }

  alias saif="ssh-add-ift"
fi

if type "tmux" > /dev/null 2>&1; then
  function tmux-attach-ift {
    if [ -n "$TMUX" ]; then
      echo 'Do not use this command in a tmux session.'
      return 1
    fi

    tmux ls > /dev/null

    if [ $? -ne 0 ]; then
      return
    fi

    local session="$(tmux list-sessions | $IFT | cut -d : -f 1)"
    if [ -n "$session" ]; then
      tmux a -t $session
    fi
  }

  alias taif="tmux-attach-ift"
fi

if type "docker" > /dev/null 2>&1; then
  function docker-exec-ift {
    local container=`docker ps | awk 'NR > 1 {print $1 "\t\t" $2 "\t\t" $NF}'`
    if [ ! -n "$container" ]; then
      echo "There is no running container"
      return
    fi
    container=`echo $container | $IFT | awk '{print $1}'`
    if [ -n "$container" ]; then
      docker exec -it $container `basename $SHELL`
      if [ $? -ne 0 ];then
        echo 'So using "bash"'
        docker exec -it $container bash
      fi
    fi
  }
  alias deif="docker-exec-ift"
fi


