#!/bin/sh

if [ -d $HOME/.anyenv ]; then
  export PATH="$HOME/.anyenv/bin:${PATH}"
  eval "$(anyenv init - --no-rehash)"
fi

#if type "pipenv" > /dev/null 2>&1; then
#  eval "$(pipenv --completion)"
#fi
