#!/bin/sh

if [ "$(uname)" = 'Darwin' ]; then
  export PATH="/usr/local/opt/openssl/bin:$PATH"
fi

export PATH="$PATH:$HOME/local/bin:$HOME/local/mybin"
export GOPATH="$HOME/go"

export CURT_SHELL=`ps -p $$ | grep -Eo '[^a..zA..Z0..9][a..z]{0,2}sh' | sed 's/\///g' | sed 's/\-//g' | sed 's/\ //g'`

