#!/bin/sh

if [ "$(uname)" = 'Darwin' ]; then
  export PATH="/usr/local/opt/openssl/bin:$PATH"
fi

export PATH="$PATH:$HOME/local/bin:$HOME/local/mybin"
export GOPATH="$HOME/go"

export CURT_SHELL=`basename $(ps -p $$ -o comm | awk 'NR==2' | sed 's/\-//g')`

