# source init files
for f in ~/.dotfiles/init_files/*
do
  source $f
done

# zinit plugin ファイル
source $HOME/.dotfiles/zsh/zinit_plugins

# emacs風のバインド
bindkey -e

### history
HISTFILE=~/.zsh_history
HISTSIZE=100000
SAVEHIST=100000
HISTTIMEFORMAT=%Y/%m/%d%H:%M:%S
setopt share_history # 同時に起動したzshの間でヒストリを共有する
setopt hist_ignore_all_dups # 同じコマンドをヒストリに残さない
setopt hist_ignore_space # スペースから始まるコマンド行はヒストリに残さない
setopt hist_reduce_blanks # ヒストリに保存するときに余分なスペースを削除する
### end of history

# 単語の区切り文字を指定する
autoload -Uz select-word-style
select-word-style default
# ここで指定した文字は単語区切りとみなされる
# / も区切りと扱うので、^W でディレクトリ１つ分を削除できる
zstyle ':zle:*' word-chars " /=;@:{},|"
zstyle ':zle:*' word-style unspecified


### 補完
# スペルミス・ワイルドカードでも展開する
zstyle ':completion:*' completer _complete _match

# 補完方法毎にグループ化する
zstyle ':completion:*' format '--- %F{yellow}%d%f ---'
zstyle ':completion:*' group-name ''

# 補完で小文字でも大文字にマッチさせる
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}' 

# 親ディレクトリからのカレントディレクトリを補完をしない
zstyle ':completion:*:cd:*' ignore-parents parent pwd

# sudo の後ろでコマンド名を補完する
zstyle ':completion:*:sudo:*' command-path /usr/local/sbin /usr/local/bin \
  /usr/sbin /usr/bin /sbin /bin /usr/X11R6/bin

# 補完候補と詳細マニュアルの間の文字列を設定
zstyle ':completion:*' list-separator '-->'

# タブ補完時にディレクトリ・ファイルを色付け
if [ -n "$LS_COLORS" ]; then
    zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
fi

###

# オプション
# 日本語ファイル名を表示可能にする
setopt print_eight_bit

# beep を無効にする
setopt no_beep

# フローコントロールを無効にする
setopt no_flow_control

# '#' 以降をコメントとして扱う
setopt interactive_comments

# 高機能なワイルドカード展開を使用する
setopt extended_glob

# no nomatch
setopt nonomatch

