#ENHANCD_DIR=
ENHANCD_FILTER="fzf:peco"
ENHANCD_COMMAND=ecd
#ENHANCD_DISABLE_DOT=
#ENHANCD_DISABLE_HYPHEN=
ENHANCD_DISABLE_HOME=1
ENHANCD_DOT_ARG="."
#ENHANCD_HYPHEN_ARG=
ENHANCD_HYPHEN_NUM=200
#ENHANCD_HOME_ARG=
ENHANCD_HOOK_AFTER_CD=
ENHANCD_USE_FUZZY_MATCH=0
#ENHANCD_COMPLETION_KEYBIND=
#ENHANCD_COMPLETION_BEHAVIOR=

function cd () {
  case $1 in
    $ENHANCD_DOT_ARG) __enhancd::cd $ENHANCD_DOT_ARG;;
    $ENHANCD_HYPHEN_ARG) __enhancd::cd $ENHANCD_HYPHEN_ARG;;
    *) __enhancd::cd::builtin $1;;
  esac
}

alias cd="cd"
