#!/bin/zsh

### Zinit
if [[ ! -f $HOME/.zinit/bin/zinit.zsh ]]; then
    print -P "%F{33}▓▒░ %F{220}Installing DHARMA Initiative Plugin Manager (zdharma/zinit)…%f"
    command mkdir -p "$HOME/.zinit" && command chmod g-rwX "$HOME/.zinit"
    command git clone https://github.com/zdharma/zinit "$HOME/.zinit/bin" && \
        print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
        print -P "%F{160}▓▒░ The clone has failed.%f%b"
fi

source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit light-mode for \
    zinit-zsh/z-a-patch-dl \
    zinit-zsh/z-a-as-monitor \
    zinit-zsh/z-a-bin-gem-node
### End of Zinit

zinit light-mode for \
  mafredri/zsh-async \
  zdharma/fast-syntax-highlighting

zinit ice blockf atload='autoload -U compinit && compinit'
zinit load zsh-users/zsh-completions

zinit ice from"gh-r" as"program" unload="type peco > /dev/null 2>&1"
zinit load peco/peco

zinit ice atload'!_zsh_git_prompt_precmd_hook' lucid \
  atload='source $HOME/.dotfiles/zsh/plugin_configs/woefe---git-prompt.zsh'
zinit load woefe/git-prompt.zsh

zinit ice compile'(pure|async).zsh' pick'async.zsh' src'pure.zsh' \
  atload='source $HOME/.dotfiles/zsh/plugin_configs/mypure.zsh'
zinit load $HOME/.dotfiles/zsh/local_plugins/mypure

zinit ice wait'2' lucid
zinit snippet $HOME/.dotfiles/zsh/local_plugins/anyenv-init.zsh

