#!/bin/zsh

zinit light mafredri/zsh-async

zinit ice atload'!_zsh_git_prompt_precmd_hook' lucid
zinit load woefe/git-prompt.zsh
ZSH_THEME_GIT_PROMPT_PREFIX="("
ZSH_THEME_GIT_PROMPT_SUFFIX=")"
ZSH_THEME_GIT_PROMPT_SEPARATOR="|"
ZSH_THEME_GIT_PROMPT_DETACHED="%{$fg_bold[cyan]%}:"
ZSH_THEME_GIT_PROMPT_BRANCH="%{$fg_bold[magenta]%}"
ZSH_THEME_GIT_PROMPT_UPSTREAM_SYMBOL="%{$fg_bold[yellow]%}⟳ "
ZSH_THEME_GIT_PROMPT_UPSTREAM_PREFIX="%{$fg[red]%}(%{$fg[yellow]%}"
ZSH_THEME_GIT_PROMPT_UPSTREAM_SUFFIX="%{$fg[red]%})"
ZSH_THEME_GIT_PROMPT_BEHIND="↓"
ZSH_THEME_GIT_PROMPT_AHEAD="↑"
ZSH_THEME_GIT_PROMPT_UNMERGED="%{$fg[red]%}×"
ZSH_THEME_GIT_PROMPT_STAGED="%{$fg[green]%}●"
ZSH_THEME_GIT_PROMPT_UNSTAGED="%{$fg[red]%}+"
ZSH_THEME_GIT_PROMPT_UNTRACKED="…"
ZSH_THEME_GIT_PROMPT_STASHED="%{$fg[blue]%}⚑"
ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg_bold[green]%}✔"
ZSH_GIT_PROMPT_SHOW_STASH=1
ZSH_GIT_PROMPT_SHOW_UPSTREAM="symbol"
ZSH_GIT_PROMPT_FORCE_BLANK=1

zinit ice compile'(pure|async).zsh' pick'async.zsh' src'pure.zsh'
zinit load $HOME/.dotfiles/zsh/local_plugins/mypure
zstyle ':prompt:pure:host' color green
zstyle ':prompt:pure:user' color green
zstyle ':prompt:pure:user:root' color red
zstyle ':prompt:pure:prompt:success' color blue

zinit ice wait'0' lucid
zinit snippet $HOME/.dotfiles/zsh/local_plugins/anyenv-init.zsh

zinit snippet 'https://raw.githubusercontent.com/sorin-ionescu/prezto/master/modules/completion/init.zsh'
zinit snippet 'https://raw.githubusercontent.com/sorin-ionescu/prezto/master/modules/command-not-found/init.zsh'
zinit light zdharma/fast-syntax-highlighting
