[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  let g:gitgutter_override_sign_column_highlight = 0
  set signcolumn=yes
  let g:gitgutter_sign_added = '+'
  let g:gitgutter_sign_modified = '~'
  let g:gitgutter_sign_removed = '_'
  let g:gitgutter_sign_removed_first_line = '‾'
  let g:gitgutter_sign_modified_removed = '‾'
  let g:gitgutter_signs = 1
  let g:gitgutter_highlight_lines = 0
  highlight link GitGutterDeleteLine Normal
  set updatetime=50
'''

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'ryanoasis/vim-devicons'
hook_add = '''
  set encoding=UTF-8
'''

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'

[[plugins]]
repo = 'junegunn/fzf.vim'
depend = 'fzf'
hook_add = '''
  command! -bang -nargs=? -complete=dir Files
    \ call fzf#vim#files(<q-args>, {'options': ['--layout=reverse', '--info=inline', '--preview', 'cat {}']}, <bang>0)
'''

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
hook_add = '''
  autocmd BufWritePre * :FixWhitespace
'''

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
depends = ['async.vim']
hook_add = '''
  set signcolumn=yes
  let g:lsp_signs_enabled = 0
  let g:lsp_diagnostics_enabled = 1
  let g:lsp_diagnostics_echo_cursor = 1
  let g:lsp_highlight_references_enabled = 1
  let g:lsp_highlights_enabled = 1
  let g:lsp_textprop_enabled = 1

  " コマンド
  nnoremap <C-]> :LspDefinition<CR>
  nnoremap <C-[> :LspReference<CR>
  nnoremap <C-j>s :LspPeekDefinition<CR>
  nnoremap <C-j>r :LspRename<CR>
  nnoremap <C-j>h :LspHover<CR>
  nnoremap <C-j>d :LspDocumentDiagnostics<CR>

  " 色
  autocmd ColorScheme * highlight lspReference ctermfg=222 guifg=#d9c767 ctermbg=65 guibg=#344134
  highlight link LspErrorHighlight ErrorMsg
'''

[[plugins]]
repo = 'mattn/vim-lsp-settings'
depends = ['async.vim', 'vim-lsp']

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'
depends = ['asyncomplete.vim', 'vim-lsp']
hook_add = '''
  autocmd FileType tagbar,nerdtree setlocal signcolumn=no
  let g:asyncomplete_auto_popup = 1
  let g:asyncomplete_popup_delay = 100
'''

