#!/bin/sh
# clearコマンドを簡略化
alias c="clear"

# ファイルの安全性を高める
alias mv="mv -i"
alias cp="cp -i"
alias rm="rm -i"

# ssh-agentの利用をしやすくする
alias ssh="ssh -A"

# シェルの再起動
alias relogin='exec $CURT_SHELL -l'

# 第一引数のファイルをクリップボードにコピー
alias clip="pbcopy <"


# dirs
alias dirs="dirs -v"

# rmtrashがインストールされていればrmコマンドをゴミ箱行きにする (rmtrashは要インストール)
if type "rmtrash" > /dev/null 2>&1; then
  echo "alias rm=""rmtrash"""  #rmtrashが存在する時の処理
  alias rm="rmtrash"
fi


# railsのエイリアス
alias rails="bundle exec rails"
alias binstall="bundle install --path vendor/bundle"
alias rmbr="/bin/rm Gemfile Gemfile.lock ;/bin/rm -rf .bundle vendor"

rnew () {
    bundle exec rails new $1 --skip-bundle
}

creategemfile () {
    if [ $# = 0 ] ; then
        cat << EOS > Gemfile
        source "http://rubygems.org"
        gem "rails"
EOS
    else
        cat << EOS > Gemfile
        source "http://rubygems.org"
        gem "rails", "$1"
EOS
    fi
}


# vscodeをコマンドラインから実行
launch-vscode () { VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCode" --args $* ;}
alias vscode="launch-vscode"
